##################################
# BACKEND
##################################
backend = "glx";
vsync = true;
use-damage = true;
log-level = "warn";

##################################
# OPACITY
##################################
detect-client-opacity = true;
use-ewmh-active-win = true;

##################################
# ROUNDED CORNERS
##################################
#corner-radius = 15;

##################################
# BLUR
##################################
blur: {
  method = "dual_kawase";
  size = 5;
  strength = 1;
};

blur-background = true;
blur-background-fixed = true;

##################################
# SHADOWS
##################################
shadow = true;
shadow-radius = 1;
shadow-opacity = 0.6;
shadow-offset-x = 0;
shadow-offset-y = 0;
shadow-color = "#393943";

##################################
# FADING
##################################
fading = true;
fade-in-step = 0.03;
fade-out-step = 0.03;
fade-delta = 3;

##################################
# RULES  (FIXED SYNTAX)
##################################
rules = (
  { match = "focused"; opacity = 1; },  
);

