#!/usr/bin/env bash

FOLDER=~/Wallpaper
WALLPAPER_SH=~/dotfiles/scripts/images-photos-wallpapers/wallpaper.sh

menu() {
        if command -v nsxiv >/dev/null; then
                CHOICE=$(nsxiv -otb $FOLDER/*)
        else
                CHOICE=$(echo -e "Random\n$(command ls -v $FOLDER)" | dmenu -c -l 15 -i -p "Wallpaper: ")
        fi

        case $CHOICE in
                Random)
                        RANDOM_WALL=$(find "$FOLDER" -type f \( -iname "*.jpg" -o -iname "*.jpeg" -o -iname "*.png" \) | shuf -n1)
                        "$WALLPAPER_SH" "$RANDOM_WALL" ;;
                *.*) "$WALLPAPER_SH" "$FOLDER/$CHOICE" ;;
                *) exit 0 ;;
        esac
}

case "$#" in
        0) menu ;;
        1) "$WALLPAPER_SH" "$1" ;;
        2) "$WALLPAPER_SH" "$1" ;;
        *) exit 0 ;;
esac
