##################################
# BACKEND
##################################
backend = "glx";
vsync = true;
use-damage = true;
log-level = "warn";

##################################
# OPACITY
##################################
detect-client-opacity = true;
use-ewmh-active-win = true;
opacity-rule = [
  "72:class_g = 'dwm' && window_type = 'dock'",
  "100:class_g = 'dwm' && window_type != 'dock'"
];

##################################
# BLUR
##################################
blur: {
  method = "dual_kawase";
  size = 8;
  strength = 4;
};
blur-background = true;
blur-background-fixed = true;
blur-background-exclude = [
  "class_g = 'slop'"
];

##################################
# SHADOWS
##################################
shadow = true;
shadow-radius = 1;
shadow-opacity = 0.6;
shadow-offset-x = 0;
shadow-offset-y = 0;
shadow-color = "#393943";

##################################
# FADING
##################################
fading = true;
fade-in-step = 0.03;
fade-out-step = 0.03;
fade-delta = 3;
